export const RESGISTER_LOADING='RESGISTER_LOADING';
export const RESGISTER_SUCCESS='RESGISTER_SUCCESS';
export const RESGISTER_FAIL='RESGISTER_FAIL';
export const CLEAR_AUTH_STATE='CLEAR_AUTH_STATE';
export const LOGIN_FAIL='LOGIN_FAIL';
export const LOGIN_LOADING='LOGIN_LOADING';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGOUT_USER='LOGOUT_USER';